site_name: Nik Framework
site_url: https://nik.githubpages.com
repo_url: https://github.com/nik-framework/nik
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  # font:
  # code: Open Sans
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
