name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    name: Lint (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Sync dependencies
        run: uv sync

      - name: Run linters
        run: bash ./scripts/lint

  test:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: bash ./scripts/test
